version: "3.7"
services:
  api:
    build: .
    command: npm start
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    ports:
      - "3000:3000"
    volumes:
      - .:/home/zedan/dev/ecommerce-api
